### ISSUE TITLE
:bug: update pipeline to support latest nf-core/tools

### ISSUE THREAD

**Issue by bunop** [cnr-ibba/nf-resequencing-mem#46]
`nf-core/tools v2.7.1` cannot lint pipeline anymore: there are some changes which could affect CI test. Pipeline need to be updated and lint test should pass without warnings:

## Additional information

pipeline name has issue: `.nf-core.yml` should change like this:

```yml
lint:
  actions_awsfulltest: False
  pipeline_todos: False
  files_exist: False
  nextflow_config:
    - manifest.name
  files_unchanged:
    - .gitignore
    - .github/workflows/linting.yml
  actions_ci: False
  merge_markers: False
  multiqc_config: False
repository_type: pipeline
```
`v2.7.1` has issue in parsing this file, the `dev` branch of `nf-core/tools` can parse this config file correctly
